### Slicing ✂️


In [1]:
#ROW SELECTION

import numpy as np

array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

#array[start:stop:step]
print(array[0:4:3])
print(array[1:4:3])
print(array[::2])
print(array[::-2])

[[ 1  2  3  4]
 [13 14 15 16]]
[[5 6 7 8]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 5  6  7  8]]


In [2]:
# COLUMN SELECTION
import numpy as np

array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[:,1])
print(array[:,-2])
print(array[1:3,1])
print(array[1:4,0])

print(array[:, 0:3])
print(array[:, 1::2])

print(array[:2, :2])
print(array[:2, 2:])
print(array[2:, :2])
print(array[2:, 2:])

[ 2  6 10 14]
[ 3  7 11 15]
[ 6 10]
[ 5  9 13]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[ 9 10]
 [13 14]]
[[11 12]
 [15 16]]


### Arithmetic ✖️

In [3]:
import numpy as np

#Scalar arithmetic

array = np.array([1,2,3])

print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 2)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[1 4 9]


In [4]:
import numpy as np

# Vectorized math func

array = np.array([1.22 ,2.67 ,3.50 ])

print(np.round(array))
print(np.pi)

[1. 3. 4.]
3.141592653589793


In [5]:
import numpy as np

# Vectorized math func

radii = np.array([1 ,2 ,3 ])

print(np.sqrt(radii))

print(np.pi * radii ** 2)  #Area of Circle


[1.         1.41421356 1.73205081]
[ 3.14159265 12.56637061 28.27433388]


In [6]:
import numpy as np

# Element-wise arthimetic

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [7]:
import numpy as np

# Comparison Opterators

scores = np.array([91, 55, 100, 73, 82, 64])

print(scores < 60)
scores[scores > 60] = 0
print(scores)

[False  True False False False False]
[ 0 55  0  0  0  0]
