### Boardcasting

Broadcasting allows NumPy to perform operations on arrays of different shapes.
with different shapes by virtually expanding dimensions
so they match thelarger array's shape.

The dimensions have the same size.
OR
One of the dimensions has a size of 1.

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)  # Broadcasting

(4,)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [5]:
import numpy as np

array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])
array2 = np.array([[1], [2], [3], [4]])
print(array1.shape)
print(array2.shape)

print(array1 * array2) 

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [6]:
import numpy as np

array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])
array2 = np.array([[1,5], [2,6], [3,7], [4,8]])
print(array1.shape)
print(array2.shape)

print(array1 * array2) 

(4, 4)
(4, 2)


ValueError: operands could not be broadcast together with shapes (4,4) (4,2) 

In [7]:
import numpy as np

array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print(array1.shape)
print(array2.shape)

print(array1 * array2) 

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### Aggregate Function

Aggregate func = Summarize data and typically 
                 return a single value

In [9]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

print(np.sum(array))  # Sum of all elements
print(np.mean(array))  # Mean of all elements
print(np.std(array))  # Standard deviation of all elements
print(np.var(array))  # Variance of all elements
print(np.min(array))  # Minimum element in the array
print(np.max(array))  # Maximum element in the array
print(np.argmin(array))  # Index of the minimum element
print(np.argmax(array))  # Index of the maximum element

55
5.5
2.8722813232690143
8.25
1
10
0
9


In [10]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

print(np.sum(array, axis=0))  # Sum of each column
print(np.sum(array, axis=1))  # Sum of each row

[ 7  9 11 13 15]
[15 40]


### Filtering

Filtering = Refers to the process of selecting elements
            from an array that match a given condition

In [22]:
import numpy as np

ages = np.array([[21, 18, 19, 20, 3, 22, 29, 10],
                 [31, 38, 69, 40, 33, 32, 11, 50]])

teenagers = ages[ages < 18] 
adults = ages[(ages >= 18) & (ages <= 65)]
oldies = ages[ages > 65]
evens = ages[ages % 2 == 0]
odds = ages[ages % 2 != 0]

print(teenagers) 
print(adults)
print(oldies)
print(evens)
print(odds)

[ 3 10 11]
[21 18 19 20 22 29 31 38 40 33 32 50]
[69]
[18 20 22 10 38 40 32 50]
[21 19  3 29 31 69 33 11]


In [24]:
import numpy as np

ages = np.array([[21, 18, 19, 20, 3, 22, 29, 10],
                 [31, 38, 69, 40, 33, 32, 11, 50]])

adults = np.where(ages >= 18, ages, 0)
print(adults) # Replaces ages < 18 with 0

[[21 18 19 20  0 22 29  0]
 [31 38 69 40 33 32  0 50]]


## Random Number Generator

In [36]:
import numpy as np

rng = np.random.default_rng() # Create a random number generator

print(rng.integers(low=1, high=101, size=(3, 4)))  # 3x4 array of random integers from 1 to 100

[[70 63 57 36]
 [26  1  8 22]
 [21 67 46 83]]


In [37]:
import numpy as np

rng = np.random.default_rng(seed=1)  # Seed for reproducibility

print(rng.integers(low=1, high=101, size=(3, 4))) 

[[48 52 76 96]
 [ 4 15 83 95]
 [25 32 87 43]]


In [42]:
import numpy as np

np.random.seed(seed=1)

print(np.random.uniform(low=-1, high=1, size=(3, 2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [66]:
import numpy as np

rng = np.random.default_rng() 

fruits = np.array(["🍍", "🍌", "🍒", "🍉", "🍑"])

fruits = rng.choice(fruits, size=(3,3))
print(fruits)

[['🍍' '🍑' '🍉']
 ['🍉' '🍍' '🍑']
 ['🍍' '🍑' '🍑']]
